version: '3'
services:
  web:
    image: ${ECR_IMAGE_URI}
    command: rails s -p 3000 -b '0.0.0.0'
    ports:
      - 3000:3000
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 1
      MYSQL_ROOT_USER: ${MYSQL_ROOT_USER}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      RDS_HOST_NAME: ${RDS_HOST_NAME}
      RAILS_MASTER_KEY: ${RAILS_MASTER_KEY}
